steps:
- name: 'ubuntu'
  id: 'cluster creation'
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "fail" > /workspace/cluster_creation_result.txt
    echo "mocked cluster creation step"
    # echo "pass" > /workspace/cluster_creation_result.txt
  waitFor: ['-']

- name: 'ubuntu'
  id: 'tests'
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "fail" > /workspace/tests_result.txt
    echo "mocked tests step"
    # echo "pass" > /workspace/tests_result.txt
  waitFor: ['cluster creation']


- name: 'ubuntu'
  id: 'cluster cleanup'
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "fail" > /workspace/cluster_cleanup_result.txt
    echo "mocked cluster cleanup step"
    echo "pass" > /workspace/cluster_cleanup_result.txt
  waitFor: ['tests']

- name: 'gcr.io/cloud-builders/curl'
  id: 'create_github_issue'
  secretEnv: ["GITHUB_TOKEN"]
  entrypoint: '/bin/bash'
  args:
  - -c
  - |

    if [[ $_GITHUB_ISSUE!="true" ]]; then
      exit 0
    fi

    failed_steps=""

    # Read the results from each step's log file
    if [[ $(cat /workspace/cluster_creation_result.txt) != "pass" ]]; then
      failed_steps+="* cluster creation\n"
    fi
    if [[ $(cat /workspace/tests_result.txt) != "pass" ]]; then
      failed_steps+="* tests\n"
    fi
    if [[ $(cat /workspace/cluster_cleanup_result.txt) != "pass" ]]; then
      failed_steps+="* cluster cleanup\n"
    fi

    # If there are any failed steps, create a GitHub Issue
    if [[ -n "$failed_steps" ]]; then
      issue_title="CI/CD Failure: Some steps have failed"
      issue_body="The following steps failed in the Cloud Build pipeline:\n\n$failed_steps"

      payload=$(printf '{"title":"%s","body":"%s","labels":["bug"]}' "$issue_title" "$issue_body")

      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $$GITHUB_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues \
        -d "$payload"
    fi
  waitFor: ['cluster cleanup']

logsBucket: gs://ai-on-gke-qss-build-logs
options:
  substitutionOption: "ALLOW_LOOSE"
  machineType: "E2_HIGHCPU_8"
availableSecrets:
  secretManager:
  - versionName: projects/ai-on-gke-qss/secrets/dmitriy-drogovoz-us-ci-gcp/versions/latest
    env: "GITHUB_TOKEN"
