steps:
- name: 'ubuntu'
  id: 'run_tests'
  entrypoint: 'bash'
  args:
  - -c
  - |
    echo "fail" > /workspace/ray_serve_gke_cluster_result.txt
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/curl'
  id: 'create_github_issue'
  entrypoint: '/bin/bash'
  args:
  - -c
  - |
    if [[ $(cat /workspace/ray_serve_gke_cluster_result.txt) != "pass" ]]; then
      curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $_GITHUB_TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/dmitriy-drogovoz-us/tutorials-and-examples/issues \
        -d '{"title":"Found a bug in CI","body":"I'\''m having a problem with this.","labels":["bug"]}'
    fi
  waitFor: ['run_tests']
logsBucket: gs://ai-on-gke-qss-build-logs
options:
  substitutionOption: "ALLOW_LOOSE"
  machineType: "E2_HIGHCPU_8"
substitutions:
  _GITHUB_TOKEN: 'projects/$PROJECT_ID/secrets/dmitriy-drogovoz-us-ci-gcp/versions/latest'
